// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenFoodFacts.Persistence.Context;

namespace OpenFoodFacts.Persistence.Migrations
{
    [DbContext(typeof(OpenFoodFactsContext))]
    partial class OpenFoodFactsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("OpenFoodFacts.Domain.Entities.FileHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinesRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalLines")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FileHistorys");
                });

            modelBuilder.Entity("OpenFoodFacts.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brands")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cities")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_t")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image_Url")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Imported_t")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients_Text")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<string>("Labels")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Last_modified_t")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Main_Category")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nutriscore_Grade")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Nutriscore_Score")
                        .HasColumnType("double(14,2)");

                    b.Property<string>("Product_name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purchase_places")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Quantity")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Serving_Quantity")
                        .HasColumnType("double(14,2)");

                    b.Property<string>("Serving_Size")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stores")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Traces")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
